---
title: The Public Good
subtitle: 
author: Jalen Poteat
framework: revealjs
revealjs: {theme: personal, transition: none}
widgets: [mathjax]
mode: selfcontained


--- {background: "#FFF1E0"}
#    The Public Good
###  Chapter 07
<br>
<small>Amaya Taylor</small><br>
<small>Jalen Poteat</small><br>
<small>Nina Wu</small><br>


--- {background: "#FFF1E0"}
## Overview

* Jefferson’s 4 Elementary Thinkers
* Federalists Papers
* Massachusetts Constitution
* Madison on Religion & Education
* Ideas of the Constitution
* Preamble




--- {background: "#FFF1E0"}
## Jefferson’s Elementary Thinkers

### Locke & Sidney
Limitation and natural rights (limited government, majority rule, and protection 
of natural rights of individuals; ideals of the enlightenment)

### Aristotle & Cicero

* Importance of govt. in human affairs, components of good govt., and the 
cruciality of concern for the public good
* “Man is a political animal”
* “A state exists for the sake of the good life, and not for the sake of life 
  only..Political society exists for the sake of noble actions, and not of mere 
  companionship”



--- {background: "#FFF1E0"}
## Federalists Papers

Argues for why government is necessary to promote the public good

Discussed In: 01, 12, 37, 57, 70, and 78

Neutralize faction to uphold the permanent and aggregate interests of the 
community (No.10)

Representatives possessing the most wisdom to discern, and the most virtue to 
pursue, the common good of the society (No.57)



--- {background: "#FFF1E0"}
## Massachusetts Constitution

Adams goal was to fulfill the common interest and to nourish the good life

3 Duties for Legislators:

1.  Cherish the interests of literature and the sciences
2.  Support and teach the principles of humanity
3.  Promote sincerity, good humor, and social affections among the people



--- {background: "#FFF1E0"}
## James Madison

### Religion
Morality is best enhanced by leaving religious worship to unestablished churches 

Ex. - Virginia’s Statute for Religious Freedom

### Education

A government without information or a means of acquiring it will lead to tragedy

”Knowledge will forever govern ignorance: And a people who mean to be their 
own Governors, must arm themselves with the power which knowledge gives.” 
- Madison (50)

Ex. Morill Act, “grant-in-aid” programs
  
